services:
  - type: web
    name: hum-sync-server
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FRONTEND_URL
        sync: false
